server:
  port: 9191



# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

wswj:
  wrench:
    config:
      register:
        host: 117.72.127.57
        port: 16379
        password: 6VfzT?g5Q
      idempotent:
        lock:
          lockType: redis
          key-prefix: customer-idempotent
      system: sws-test-system